config/routes.rb
Rockr::Application.routes.draw do
  root :to => 'home#index'
  resources :venues, :concerts
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :artist, :date
  belongs_to :venue, :inverse_of => :concerts
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Venue < ActiveRecord::Base
  attr_accessible :name
  has_many :concerts, :inverse_of => :venue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def new
    @concert = Concert.new
    @venues = Venue.order(:name)
  end
  def create
    @concert = Concert.create(params[:concert])
    venue = Venue.find(params[:venues].to_i)
    @concert.venue = venue
    @concert.save
    @venues = Venue.order(:name)
    @concerts = Concert.order(:date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @venues = Venue.order(:name)
    @concerts = Concert.order(:date)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def new
    @venue = Venue.new
  end
  def create
    @venue = Venue.create(params[:venue])
    @venues = Venue.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/concerts/_form.html.haml
= form_for @concert, :remote => true do |f|
  = f.label :artist
  = f.text_field :artist, :autofocus => true
  = f.label :date
  = f.text_field :date
  = f.label :venue
  = select_tag "venues", options_from_collection_for_select(@venues, "id", "name")
  = button_to_function('Cancel', 'cancel_concert_form()')
  = f.submit

app/views/concerts/_list.html.haml
- @concerts.each do |concert|
  %li
  = concert.try(:artist)
  = concert.try(:date)
  = concert.try(:venue).try(:name)

app/views/concerts/create.js.erb
$('#concert_form').empty();
$('#concerts').empty();
$('#concerts').append('<%=j render :partial => 'list' %>');

app/views/concerts/new.js.erb
$('#concert_form').empty().append('<%=j render :partial => 'form' %>');

app/views/home/_list.html.haml
- if @venues != nil
  - @venues.each do |venue|
    %li
      = venue.name
      - if venue.concerts != nil
        - venue.concerts.order(:date) do |concert|
          %ul
            %li= concert.artist
            %li= concert.date

app/views/home/index.html.haml
= link_to('New Venue', new_venue_path, :remote => true)
= link_to('New Concert', new_concert_path, :remote => true)
#venue_form
#concert_form
%ol#concerts
  = render :partial => 'home/list'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rockr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/venues/_form.html.haml
= form_for @venue, :remote => true do |f|
  = f.label :name
  = f.text_field :name, :autofocus => true
  = button_to_function('Cancel', 'cancel_venue_form()')
  = f.submit

app/views/venues/create.js.erb
$('#venue_form').empty()
$('#concerts').empty()
$('#concerts').append('<%=j render(:partial => 'home/list') %>');

app/views/venues/new.js.erb
$('#venue_form').empty().append('<%=j render(:partial => 'form') %>')